### ISSUE TITLE
File extensions

### ISSUE THREAD

**Issue by TriMoon** [SavageCore/atom-uglify-es#3]
Need a way to configure file extensions on which this module works.
For example my (Module) Javascripts end with `.mjs`

**Comment by SavageCore** [comment]
I only check for grammar of JavaScript so if you choose grammar/language for `.mjs` files it should just work.

**Comment by TriMoon** [comment]
I tried using CTRL-ALT-M on a mjs file and it didn't do anything, but it did with js extension, thats why...

**Comment by SavageCore** [comment]
Yes, as expected.

Open `mjs` file and along the bottom status bar next to encoding (UTF etc.) select `JavaScript`. Should then work.

Interesting though as I've just installed Atom plus this extension and it supports `mjs` out of the box. Switched to VS Code myself so my Atom plugins are on life support!

**Comment by TriMoon** [comment]
Same here im on VSC these days also :wink:
